### ISSUE TITLE
slc not found

### ISSUE THREAD

**Issue by jgrenat** [strongloop-community/vagrant-strongnode-mongodb#1]
Hello,

First, thanks for this vagrant box. 

I have a problem after installing it, when I try to make a `slc run`, I have an error message `slc: command not found.

Does anyone have the same issue ?

**Comment by rmg** [comment]
This box looks pretty out of date. It uses our custom node distribution which has since been replaced with a combination of upstream node and our strongloop module installed from npm.

I'll see if I can update it, but it will have to wait until I get home. The strongbox repo doesn't have mongodb, but it might be faster to get up and running than waiting for me.

**Comment by rmg** [comment]
I've updated the Vagrantfile and bootstrapping script and tried to retain the original intent.

**Comment by jgrenat** [comment]
Thanks for the update ! ;-)
